### ISSUE TITLE
Rails 5.1 - undefined method `alias_method_chain'

### ISSUE THREAD

**Issue by fabianoarruda** [lightyear/sql-logging#24]
`alias_method_chain` is now deprecated and no longer works in Rails 5.1; therefore the gem is incompatible with Rails 5.1. There is at least one place where it is using the deprecated method, and it needs to be refactored to use an alternative. For reference this is the error when trying to use `sql-logging` with rails 5.1:

```
/Users/fabiano/.rvm/gems/ruby-2.3.1@clouddentistry/gems/sql-logging-3.0.10/lib/sql-logging/adapters/cache_extension.rb:20:in `<module:QueryCache>': undefined method `alias_method_chain' for ActiveRecord::ConnectionAdapters::QueryCache:Module (NoMethodError)
Did you mean?  alias_method

```

I'm taking a look at the code and maybe I can create a PR to fix it. Is this gem still maintained?

**Comment by tjoyal** [comment]
I do still use the gem and would help getting PRs through.

I presume you are looking at the version on Rubygems? Have you looked at the last commit on master? https://github.com/lightyear/sql-logging/commit/281ecc06e1fc50e0b48765a7cf7067f48225544b 

I guess it could use a version release

**Comment by fabianoarruda** [comment]
That's right @tjoyal , I just tested last rubygems version. Let me try what you suggested. Thanks!

**Comment by UnConundrum** [comment]
Is that last commit going to be merged into the gem?   I'm still getting the error.

**Comment by asnad** [comment]
I was able to fix with `gem 'sql-logging', git: 'https://github.com/lightyear/sql-logging.git', branch: 'master'`

**Comment by tjoyal** [comment]
Sorry about the delay. I published 3.0.11. Took a little bit more work than I was expecting.
